name: super_emby
services:
  super_emby:
    cpu_shares: 90
    devices:
      - /dev/dri:/dev/dri
    environment:
      - AMDGPU_IDS=/share/libdrm/amdgpu.ids
      - FONTCONFIG_PATH=/etc/fonts
      - GID=0
      - GIDLIST=0
      - HOME=/tmp
      - IGNORE_VAAPI_ENABLED_FLAG=false
      - LANG=en_US.UTF-8
      - LD_LIBRARY_PATH=/lib:/system
      - LIBVA_DRIVERS_PATH=/lib/dri
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - OCL_ICD_VENDORS=/etc/OpenCL/vendors
      - OPENAI_API_KEY=sk-xxxxxx
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PCI_IDS_PATH=/share/hwdata/pci.ids
      - PGID=0
      - PUID=0
      - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
      - UID=0
      - XDG_CACHE_HOME=/config/cache
    image: amilys/embyserver:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Emby_C.png
    ports:
      - target: 8096
        published: "8096"
        protocol: tcp
      - target: 8920
        published: "8920"
        protocol: tcp
    privileged: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/emby
        target: /config
      - type: bind
        source: /DATA/Media
        target: /media
    x-casaos:
      devices:
        - container: /dev/dri
          description:
            en_us: ""
      ports:
        - container: "8096"
          description:
            en_us: ""
        - container: "8920"
          description:
            en_us: ""
      volumes:
        - container: /config
          description:
            en_us: ""
        - container: /media
          description:
            en_us: ""
    deploy:
      resources:
        limits:
          memory: 15733M
x-casaos:
  architectures:
    - amd64
  author: CasaOS User
  category: Media
  description:
    en_us: ""
  developer: amilys
  icon: https://cdn.jsdelivr.net/gh/xushier/HD-Icons/border-radius/Emby_C.png
  image: null
  is_uncontrolled: false
  main: super_emby
  port_map: "8096"
  scheme: http
  tagline:
    en_us: Super Emby
  thumbnail: ""
  tips:
    en_us: ""
    zh_cn: |
      Emby设置->Emby Premiere：输入疯狂星期四V我50点下保存
      刷新浏览器网页开始食用
      电视直播：添加直播源后,再手动刷新一下指南数据
  title:
    en_us: Super Emby
